# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/iwtm952/Downloads/thesis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/iwtm952/Downloads/thesis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/iwtm952/Downloads/thesis/CMakeFiles /home/iwtm952/Downloads/thesis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/iwtm952/Downloads/thesis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named crack

# Build rule for target.
crack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crack
.PHONY : crack

# fast build rule for target.
crack/fast:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/build
.PHONY : crack/fast

source/ElasticProblem.o: source/ElasticProblem.cpp.o

.PHONY : source/ElasticProblem.o

# target to build an object file
source/ElasticProblem.cpp.o:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/source/ElasticProblem.cpp.o
.PHONY : source/ElasticProblem.cpp.o

source/ElasticProblem.i: source/ElasticProblem.cpp.i

.PHONY : source/ElasticProblem.i

# target to preprocess a source file
source/ElasticProblem.cpp.i:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/source/ElasticProblem.cpp.i
.PHONY : source/ElasticProblem.cpp.i

source/ElasticProblem.s: source/ElasticProblem.cpp.s

.PHONY : source/ElasticProblem.s

# target to generate assembly for a file
source/ElasticProblem.cpp.s:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/source/ElasticProblem.cpp.s
.PHONY : source/ElasticProblem.cpp.s

source/constitutive.o: source/constitutive.cpp.o

.PHONY : source/constitutive.o

# target to build an object file
source/constitutive.cpp.o:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/source/constitutive.cpp.o
.PHONY : source/constitutive.cpp.o

source/constitutive.i: source/constitutive.cpp.i

.PHONY : source/constitutive.i

# target to preprocess a source file
source/constitutive.cpp.i:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/source/constitutive.cpp.i
.PHONY : source/constitutive.cpp.i

source/constitutive.s: source/constitutive.cpp.s

.PHONY : source/constitutive.s

# target to generate assembly for a file
source/constitutive.cpp.s:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/source/constitutive.cpp.s
.PHONY : source/constitutive.cpp.s

source/main.o: source/main.cpp.o

.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i

.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s

.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/others.o: source/others.cpp.o

.PHONY : source/others.o

# target to build an object file
source/others.cpp.o:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/source/others.cpp.o
.PHONY : source/others.cpp.o

source/others.i: source/others.cpp.i

.PHONY : source/others.i

# target to preprocess a source file
source/others.cpp.i:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/source/others.cpp.i
.PHONY : source/others.cpp.i

source/others.s: source/others.cpp.s

.PHONY : source/others.s

# target to generate assembly for a file
source/others.cpp.s:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/source/others.cpp.s
.PHONY : source/others.cpp.s

source/parameter.o: source/parameter.cpp.o

.PHONY : source/parameter.o

# target to build an object file
source/parameter.cpp.o:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/source/parameter.cpp.o
.PHONY : source/parameter.cpp.o

source/parameter.i: source/parameter.cpp.i

.PHONY : source/parameter.i

# target to preprocess a source file
source/parameter.cpp.i:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/source/parameter.cpp.i
.PHONY : source/parameter.cpp.i

source/parameter.s: source/parameter.cpp.s

.PHONY : source/parameter.s

# target to generate assembly for a file
source/parameter.cpp.s:
	$(MAKE) -f CMakeFiles/crack.dir/build.make CMakeFiles/crack.dir/source/parameter.cpp.s
.PHONY : source/parameter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... crack"
	@echo "... source/ElasticProblem.o"
	@echo "... source/ElasticProblem.i"
	@echo "... source/ElasticProblem.s"
	@echo "... source/constitutive.o"
	@echo "... source/constitutive.i"
	@echo "... source/constitutive.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/others.o"
	@echo "... source/others.i"
	@echo "... source/others.s"
	@echo "... source/parameter.o"
	@echo "... source/parameter.i"
	@echo "... source/parameter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

